version: '3'

services:

  app:
    build: .
    command: >
      python -u estimate.py
        --sector=commercial
        --file=acs_hf.csv --tag=acs_hf
        --file=acs_uis.csv --tag=acs_uis
        --file=cbecs_elec.csv --tag=cbecs_elec
        --file=cbecs_foil.csv --tag=cbecs_foil
        --file=cbecs_ng.csv --tag=cbecs_ng
        --file=cbecs_sources.csv --tag=cbecs_sources
        --file=eowld.csv --tag=eowld
        --file=masssave_ci.csv --tag=masssave_ci
        --file=masssave_res.csv --tag=masssave_res
        --file=mecs_ami.csv --tag=mecs_ami
        --file=mecs_fce.csv --tag=mecs_fce
        --file=recs_hfc.csv --tag=recs_hfc
        --file=recs_hfe.csv --tag=recs_hfe
        --file=recs_sc.csv --tag=recs_sc
    env_file:
      - .env
    volumes: 
      - .:/usr/src/app
